name: APThreshold
channels:
  - defaults
dependencies:
  - python=3.11  # Python 3.13 不建议用在生产环境，兼容性差
  - numpy
  - scikit-learn
  - h5py
  - pip
  - pip:
      - unicodeit
      - scipy
      - cma
      - pyside6  # 最新版，包含 QtWebEngin
      - matplotlib
