# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate_feature_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_paras_of_features(object):
    def setupUi(self, Form_paras_of_features):
        Form_paras_of_features.setObjectName("Form_paras_of_features")
        Form_paras_of_features.resize(434, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/APThrehold_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_paras_of_features.setWindowIcon(icon)
        Form_paras_of_features.setStyleSheet("QWidget#Form_paras_of_features {background-color: #E4F4FE}")
        self.gridLayout = QtWidgets.QGridLayout(Form_paras_of_features)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_save = QtWidgets.QPushButton(Form_paras_of_features)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 0, 1, 1)
        self.pushButton_canel = QtWidgets.QPushButton(Form_paras_of_features)
        self.pushButton_canel.setObjectName("pushButton_canel")
        self.gridLayout.addWidget(self.pushButton_canel, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form_paras_of_features)
        self.tabWidget.setStyleSheet("QTabWidget#tabWidget_main::tab-bar {\n"
"    alignment: left; /* 将 Tab 标签对齐到左边 */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: white; /* 未选中的标签背景颜色为白色 */\n"
"    min-width: 145px;\n"
"    margin-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"/* 设置选中的标签背景颜色为 lightblue */\n"
"QTabBar::tab:selected {\n"
"    background-color: lightblue; /* 选中的标签背景颜色为 lightblue */\n"
"    color: black; /* 选中的标签文字颜色为黑色（可选） */\n"
"}\n"
"\n"
"/* 设置未选中的标签背景颜色为白色 */\n"
"QTabBar::tab:!selected {\n"
"    background-color: white; /* 未选中的标签背景颜色为白色 */\n"
"    color: black; /* 未选中的标签文字颜色为黑色（可选） */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_time_average_Vm = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_time_average_Vm.setObjectName("doubleSpinBox_time_average_Vm")
        self.gridLayout_2.addWidget(self.doubleSpinBox_time_average_Vm, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.doubleSpinBox_time_dvdt = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_time_dvdt.setObjectName("doubleSpinBox_time_dvdt")
        self.gridLayout_4.addWidget(self.doubleSpinBox_time_dvdt, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_average_dvdt = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_average_dvdt.setObjectName("radioButton_average_dvdt")
        self.gridLayout_3.addWidget(self.radioButton_average_dvdt, 0, 0, 1, 1)
        self.radioButton_maximum = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_maximum.setObjectName("radioButton_maximum")
        self.gridLayout_3.addWidget(self.radioButton_maximum, 2, 0, 1, 1)
        self.radioButton_slope_two_points = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_slope_two_points.setObjectName("radioButton_slope_two_points")
        self.gridLayout_3.addWidget(self.radioButton_slope_two_points, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(Form_paras_of_features)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_paras_of_features)

    def retranslateUi(self, Form_paras_of_features):
        _translate = QtCore.QCoreApplication.translate
        Form_paras_of_features.setWindowTitle(_translate("Form_paras_of_features", "Set parameters"))
        self.pushButton_save.setText(_translate("Form_paras_of_features", "Calculate"))
        self.pushButton_canel.setText(_translate("Form_paras_of_features", "Canel"))
        self.label_2.setText(_translate("Form_paras_of_features", "ms"))
        self.label.setText(_translate("Form_paras_of_features", "Time period preceding each spike"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form_paras_of_features", "<V>"))
        self.label_3.setText(_translate("Form_paras_of_features", "Time period preceding each spike"))
        self.label_4.setText(_translate("Form_paras_of_features", "ms"))
        self.groupBox.setTitle(_translate("Form_paras_of_features", "Options"))
        self.radioButton_average_dvdt.setText(_translate("Form_paras_of_features", "Average of dVm/dt over a time period"))
        self.radioButton_maximum.setText(_translate("Form_paras_of_features", "Maximum of dVm/dt during upstroke"))
        self.radioButton_slope_two_points.setText(_translate("Form_paras_of_features", "Slope of Vm within a time period"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form_paras_of_features", "dV/dt"))
import apprcc_rc
